(* Autogenerated cert for < ab | aaaaaa = abaaba > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::0;0;0;0;0;0], [::0;1;0;0;1;0])].

Definition present_final := make_pres [::0;1]
  [:: ([::0;1;0;0;1;0], [::0;0;0;0;0;0]);
      ([::0;1;0;0;0;0;0;0;0], [::0;0;0;0;0;0;0;1;0])].

Definition cert : pres_cert := [:: add_rel [::0;1;0;0;1;0] [::0;0;0;0;0;0]
     [:: RTriple 0 0 false];
     add_rel [::0;1;0;0;0;0;0;0;0] [::0;0;0;0;0;0;0;1;0]
     [:: RTriple 0 3 true;
         RTriple 1 0 true];
     rm_rel 0
     [:: RTriple 0 0 false]].

Definition final_order := [::0;1].

Load "theories/certs/footer.v".
