(* Autogenerated cert for < ab | aabbabb = aaababbbab > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::0;0;1;1;0;1;1], [::0;0;0;1;0;1;1;1;0;1])].

Definition present_final := make_pres [::0;1]
  [:: ([::0;0;0;1;0;1;1;1;0;1], [::0;0;1;1;0;1;1])].

Definition cert : pres_cert := [:: add_rel [::0;0;0;1;0;1;1;1;0;1] [::0;0;1;1;0;1;1]
     [:: RTriple 0 0 false];
     rm_rel 0
     [:: RTriple 0 0 false]].

Definition final_order := [::0;1].

Load "theories/certs/footer.v".
