(* Autogenerated cert for < ba | ababaaa = abaabab > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::0;1;0;1;0;0;0], [::0;1;0;0;1;0;1])].

Definition present_final := make_pres [::1;0;2]
  [:: ([::0;1;0;1;0;0], [::2]);
      ([::2;0;0;0], [::0;1;0;2]);
      ([::2;1;0;1], [::0;1;2;0]);
      ([::2;0;0;1;0;0], [::0;1;0;0;1;2]);
      ([::0;1;0;0;1;0;1], [::2;0]);
      ([::2;1;0;0;1;0;1], [::0;1;0;1;0;2;0])].

Definition cert : pres_cert := [:: add_gen 2 [::0;1;0;1;0;0];
     add_rel [::2;0;0;0] [::0;1;0;2]
     [:: RTriple 1 0 false;
         RTriple 0 0 true;
         RTriple 1 3 true];
     add_rel [::2;1;0;1] [::0;1;2;0]
     [:: RTriple 1 0 false;
         RTriple 0 2 false;
         RTriple 1 2 true];
     add_rel [::2;0;0;1;0;0] [::0;1;0;0;1;2]
     [:: RTriple 1 0 false;
         RTriple 0 0 true;
         RTriple 1 5 true];
     add_rel [::0;1;0;0;1;0;1] [::2;0]
     [:: RTriple 0 0 false;
         RTriple 1 0 true];
     add_rel [::2;1;0;0;1;0;1] [::0;1;0;1;0;2;0]
     [:: RTriple 1 0 false;
         RTriple 0 5 false;
         RTriple 1 5 true];
     rm_rel 0
     [:: RTriple 0 0 true;
         RTriple 4 0 false]].

Definition final_order := [::1;0;2].

Load "theories/certs/footer.v".
