(* Autogenerated cert for < ba | baaabba = abbaababa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;0;0;0;1;1;0], [::0;1;1;0;0;1;0;1;0])].

Definition present_final := make_pres [::1;0;2;3]
  [:: ([::0;0;1;0;1], [::2]);
      ([::0;1;1], [::3]);
      ([::0;0;1;3], [::2;1]);
      ([::1;0;0;3;0], [::3;2;0]);
      ([::1;0;0;3;2], [::3;2;2]);
      ([::1;0;0;3;3], [::3;2;3]);
      ([::3;0;0;3;0], [::0;1;3;2;0]);
      ([::3;0;0;3;2], [::0;1;3;2;2]);
      ([::3;0;0;3;3], [::0;1;3;2;3]);
      ([::1;0;2;1;2;0], [::3;2;0;0;3;0]);
      ([::1;0;2;1;2;2], [::3;2;0;0;3;2]);
      ([::1;0;2;1;2;3], [::3;2;0;0;3;3]);
      ([::0;0;1;0;3;2;0], [::2;0;0;3;0]);
      ([::0;0;1;0;3;2;2], [::2;0;0;3;2]);
      ([::0;0;1;0;3;2;3], [::2;0;0;3;3]);
      ([::2;1;2;0;0;3;0], [::0;3;0;2;1;2;0]);
      ([::2;1;2;0;0;3;2], [::0;3;0;2;1;2;2]);
      ([::2;1;2;0;0;3;3], [::0;3;0;2;1;2;3]);
      ([::0;1;3;2;0;0;3;0], [::3;0;2;1;2;0]);
      ([::0;1;3;2;0;0;3;2], [::3;0;2;1;2;2]);
      ([::0;1;3;2;0;0;3;3], [::3;0;2;1;2;3])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;1;0;1];
     add_gen 3 [::0;1;1];
     add_rel [::0;0;1;3] [::2;1]
     [:: RTriple 2 3 false;
         RTriple 1 0 true];
     add_rel [::1;0;0;3;0] [::3;2;0]
     [:: RTriple 2 3 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;3;2] [::3;2;2]
     [:: RTriple 2 3 false;
         RTriple 1 6 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true;
         RTriple 1 2 true];
     add_rel [::1;0;0;3;3] [::3;2;3]
     [:: RTriple 2 3 false;
         RTriple 2 6 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true;
         RTriple 2 2 true];
     add_rel [::3;0;0;3;0] [::0;1;3;2;0]
     [:: RTriple 2 0 false;
         RTriple 2 5 false;
         RTriple 0 2 true;
         RTriple 2 2 true;
         RTriple 1 3 true];
     add_rel [::3;0;0;3;2] [::0;1;3;2;2]
     [:: RTriple 2 0 false;
         RTriple 2 5 false;
         RTriple 1 8 false;
         RTriple 0 2 true;
         RTriple 2 2 true;
         RTriple 1 3 true;
         RTriple 1 4 true];
     add_rel [::3;0;0;3;3] [::0;1;3;2;3]
     [:: RTriple 2 0 false;
         RTriple 2 5 false;
         RTriple 2 8 false;
         RTriple 0 2 true;
         RTriple 2 2 true;
         RTriple 1 3 true;
         RTriple 2 4 true];
     add_rel [::1;0;2;1;2;0] [::3;2;0;0;3;0]
     [:: RTriple 1 2 false;
         RTriple 1 8 false;
         RTriple 0 5 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true;
         RTriple 2 4 true];
     add_rel [::1;0;2;1;2;2] [::3;2;0;0;3;2]
     [:: RTriple 1 2 false;
         RTriple 1 8 false;
         RTriple 1 13 false;
         RTriple 0 5 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true;
         RTriple 2 4 true;
         RTriple 1 5 true];
     add_rel [::1;0;2;1;2;3] [::3;2;0;0;3;3]
     [:: RTriple 1 2 false;
         RTriple 1 8 false;
         RTriple 2 13 false;
         RTriple 0 5 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true;
         RTriple 2 4 true;
         RTriple 2 5 true];
     add_rel [::0;0;1;0;3;2;0] [::2;0;0;3;0]
     [:: RTriple 2 4 false;
         RTriple 1 7 false;
         RTriple 0 4 false;
         RTriple 1 0 true;
         RTriple 2 3 true];
     add_rel [::0;0;1;0;3;2;2] [::2;0;0;3;2]
     [:: RTriple 2 4 false;
         RTriple 1 7 false;
         RTriple 1 12 false;
         RTriple 0 4 false;
         RTriple 1 0 true;
         RTriple 2 3 true;
         RTriple 1 4 true];
     add_rel [::0;0;1;0;3;2;3] [::2;0;0;3;3]
     [:: RTriple 2 4 false;
         RTriple 1 7 false;
         RTriple 2 12 false;
         RTriple 0 4 false;
         RTriple 1 0 true;
         RTriple 2 3 true;
         RTriple 2 4 true];
     add_rel [::2;1;2;0;0;3;0] [::0;3;0;2;1;2;0]
     [:: RTriple 1 0 false;
         RTriple 1 6 false;
         RTriple 0 3 false;
         RTriple 2 1 true;
         RTriple 2 9 false;
         RTriple 0 6 true;
         RTriple 1 3 true;
         RTriple 1 5 true];
     add_rel [::2;1;2;0;0;3;2] [::0;3;0;2;1;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 6 false;
         RTriple 0 3 false;
         RTriple 2 1 true;
         RTriple 2 9 false;
         RTriple 1 12 false;
         RTriple 0 6 true;
         RTriple 1 3 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     add_rel [::2;1;2;0;0;3;3] [::0;3;0;2;1;2;3]
     [:: RTriple 1 0 false;
         RTriple 1 6 false;
         RTriple 0 3 false;
         RTriple 2 1 true;
         RTriple 2 9 false;
         RTriple 2 12 false;
         RTriple 0 6 true;
         RTriple 1 3 true;
         RTriple 1 5 true;
         RTriple 2 6 true];
     add_rel [::0;1;3;2;0;0;3;0] [::3;0;2;1;2;0]
     [:: RTriple 2 2 false;
         RTriple 1 5 false;
         RTriple 0 2 false;
         RTriple 2 0 true;
         RTriple 2 8 false;
         RTriple 0 5 true;
         RTriple 1 2 true;
         RTriple 1 4 true];
     add_rel [::0;1;3;2;0;0;3;2] [::3;0;2;1;2;2]
     [:: RTriple 2 2 false;
         RTriple 1 5 false;
         RTriple 0 2 false;
         RTriple 2 0 true;
         RTriple 2 8 false;
         RTriple 1 11 false;
         RTriple 0 5 true;
         RTriple 1 2 true;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::0;1;3;2;0;0;3;3] [::3;0;2;1;2;3]
     [:: RTriple 2 2 false;
         RTriple 1 5 false;
         RTriple 0 2 false;
         RTriple 2 0 true;
         RTriple 2 8 false;
         RTriple 2 11 false;
         RTriple 0 5 true;
         RTriple 1 2 true;
         RTriple 1 4 true;
         RTriple 2 5 true];
     rm_rel 0
     [:: RTriple 1 3 true;
         RTriple 3 0 true;
         RTriple 1 0 false;
         RTriple 0 3 false]].

Definition final_order := [::0;3;1;2].

Load "theories/certs/footer.v".
