(* Autogenerated cert for < ab | baabbbabaa = aaaaaabaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::1;0;0;1;1;1;0;1;0;0], [::0;0;0;0;0;0;1;0;0])].

Definition present_final := make_pres [::0;1;2]
  [:: ([::0;0;0;0;0;0;1], [::2]);
      ([::1;0;0;1;1;1;0;1;2], [::2;2]);
      ([::1;0;0;1;1;1;0;2;2], [::0;0;0;0;0;0;2;2]);
      ([::2;0;0;1;1;1;0;1;2], [::0;0;0;0;0;0;2;2]);
      ([::1;0;0;1;1;1;0;1;0;0], [::2;0;0]);
      ([::1;0;0;1;1;1;0;1;0;2], [::2;0;2]);
      ([::1;0;0;1;1;1;0;2;0;0], [::0;0;0;0;0;0;2;0;0]);
      ([::1;0;0;1;1;1;0;2;0;2], [::0;0;0;0;0;0;2;0;2]);
      ([::2;0;0;1;1;1;0;1;0;0], [::1;0;0;1;1;1;0;2;0;0]);
      ([::2;0;0;1;1;1;0;1;0;2], [::0;0;0;0;0;0;2;0;2]);
      ([::0;0;0;0;0;0;0;0;0;0;0;0;2;2], [::2;0;0;1;1;1;0;2;2]);
      ([::0;0;0;0;0;0;0;0;0;0;0;0;2;0;0], [::2;0;0;1;1;1;0;2;0;0]);
      ([::0;0;0;0;0;0;0;0;0;0;0;0;2;0;2], [::2;0;0;1;1;1;0;2;0;2]);
      ([::1;0;0;1;1;1;0;0;0;0;0;0;0;2;2], [::2;0;0;1;1;1;0;2;2]);
      ([::2;0;0;1;1;1;0;0;0;0;0;0;0;2;2], [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;2]);
      ([::1;0;0;1;1;1;0;0;0;0;0;0;0;2;0;0], [::2;0;0;1;1;1;0;2;0;0]);
      ([::1;0;0;1;1;1;0;0;0;0;0;0;0;2;0;2], [::2;0;0;1;1;1;0;2;0;2]);
      ([::2;0;0;1;1;1;0;0;0;0;0;0;0;2;0;0], [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;0;0]);
      ([::2;0;0;1;1;1;0;0;0;0;0;0;0;2;0;2], [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;0;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;0;0;0;0;1];
     add_rel [::1;0;0;1;1;1;0;1;2] [::2;2]
     [:: RTriple 1 8 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;1;1;0;2;2] [::0;0;0;0;0;0;2;2]
     [:: RTriple 1 7 false;
         RTriple 1 14 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 1 7 true];
     add_rel [::2;0;0;1;1;1;0;1;2] [::0;0;0;0;0;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 14 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 1 7 true];
     add_rel [::1;0;0;1;1;1;0;1;0;0] [::2;0;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;0;0;1;1;1;0;1;0;2] [::2;0;2]
     [:: RTriple 1 9 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 2 true];
     add_rel [::1;0;0;1;1;1;0;2;0;0] [::0;0;0;0;0;0;2;0;0]
     [:: RTriple 1 7 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 0 6 true;
         RTriple 1 6 true];
     add_rel [::1;0;0;1;1;1;0;2;0;2] [::0;0;0;0;0;0;2;0;2]
     [:: RTriple 1 7 false;
         RTriple 1 15 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 1 8 true];
     add_rel [::2;0;0;1;1;1;0;1;0;0] [::1;0;0;1;1;1;0;2;0;0]
     [:: RTriple 1 0 false;
         RTriple 0 0 false;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::2;0;0;1;1;1;0;1;0;2] [::0;0;0;0;0;0;2;0;2]
     [:: RTriple 1 0 false;
         RTriple 1 15 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 1 8 true];
     add_rel [::0;0;0;0;0;0;0;0;0;0;0;0;2;2] [::2;0;0;1;1;1;0;2;2]
     [:: RTriple 1 12 false;
         RTriple 1 19 false;
         RTriple 0 12 false;
         RTriple 0 6 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 8 true];
     add_rel [::0;0;0;0;0;0;0;0;0;0;0;0;2;0;0] [::2;0;0;1;1;1;0;2;0;0]
     [:: RTriple 1 12 false;
         RTriple 0 12 false;
         RTriple 0 6 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::0;0;0;0;0;0;0;0;0;0;0;0;2;0;2] [::2;0;0;1;1;1;0;2;0;2]
     [:: RTriple 1 12 false;
         RTriple 1 20 false;
         RTriple 0 12 false;
         RTriple 0 6 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 9 true];
     add_rel [::1;0;0;1;1;1;0;0;0;0;0;0;0;2;2] [::2;0;0;1;1;1;0;2;2]
     [:: RTriple 1 13 false;
         RTriple 1 20 false;
         RTriple 0 13 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 8 true];
     add_rel [::2;0;0;1;1;1;0;0;0;0;0;0;0;2;2] [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 19 false;
         RTriple 1 26 false;
         RTriple 0 19 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 0 13 true;
         RTriple 1 13 true;
         RTriple 1 14 true];
     add_rel [::1;0;0;1;1;1;0;0;0;0;0;0;0;2;0;0] [::2;0;0;1;1;1;0;2;0;0]
     [:: RTriple 1 13 false;
         RTriple 0 13 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::1;0;0;1;1;1;0;0;0;0;0;0;0;2;0;2] [::2;0;0;1;1;1;0;2;0;2]
     [:: RTriple 1 13 false;
         RTriple 1 21 false;
         RTriple 0 13 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 9 true];
     add_rel [::2;0;0;1;1;1;0;0;0;0;0;0;0;2;0;0] [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;0;0]
     [:: RTriple 1 0 false;
         RTriple 1 19 false;
         RTriple 0 19 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 0 13 true;
         RTriple 1 13 true];
     add_rel [::2;0;0;1;1;1;0;0;0;0;0;0;0;2;0;2] [::0;0;0;0;0;0;2;0;0;1;1;1;0;2;0;2]
     [:: RTriple 1 0 false;
         RTriple 1 19 false;
         RTriple 1 27 false;
         RTriple 0 19 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 0 13 true;
         RTriple 1 13 true;
         RTriple 1 15 true];
     rm_rel 0
     [:: RTriple 4 0 true;
         RTriple 0 0 false]].

Definition final_order := [::0;1;2].

Load "theories/certs/footer.v".
