(* Autogenerated cert for < ba | baaba = ababaaaaba > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;0;0;1;0], [::0;1;0;1;0;0;0;0;1;0])].

Definition present_final := make_pres [::1;0;2;3]
  [:: ([::0;1;0;1;0;0;0], [::3]);
      ([::1;0;2], [::3;2]);
      ([::1;0;3], [::3;3]);
      ([::3;0;1], [::2]);
      ([::3;0;3;2], [::2;0;2]);
      ([::3;0;3;3], [::2;0;3]);
      ([::1;0;0;1;0], [::2;0]);
      ([::1;0;0;1;2], [::2;2]);
      ([::1;0;0;1;3], [::2;3]);
      ([::1;0;0;2;0], [::3;0;2;0]);
      ([::1;0;0;2;2], [::3;0;2;2]);
      ([::1;0;0;2;3], [::3;0;2;3]);
      ([::1;0;0;3;2], [::2;0;2]);
      ([::1;0;0;3;3], [::2;0;3]);
      ([::2;0;0;1;0], [::1;0;0;2;0]);
      ([::2;0;0;1;2], [::3;0;2;2]);
      ([::2;0;0;1;3], [::3;0;2;3]);
      ([::3;0;2;0;2], [::2;0;0;3;2]);
      ([::3;0;2;0;3], [::2;0;0;3;3]);
      ([::2;0;1;0;0;0], [::3;3]);
      ([::3;0;3;0;2;0], [::2;0;0;2;0]);
      ([::3;0;3;0;2;2], [::2;0;0;2;2]);
      ([::3;0;3;0;2;3], [::2;0;0;2;3]);
      ([::1;0;0;3;0;2;0], [::2;0;0;2;0]);
      ([::1;0;0;3;0;2;2], [::2;0;0;2;2]);
      ([::1;0;0;3;0;2;3], [::2;0;0;2;3]);
      ([::3;0;2;0;0;2;0], [::2;0;0;3;0;2;0]);
      ([::3;0;2;0;0;2;2], [::2;0;0;3;0;2;2]);
      ([::3;0;2;0;0;2;3], [::2;0;0;3;0;2;3]);
      ([::3;0;2;0;0;3;2], [::2;0;0;2;0;2]);
      ([::3;0;2;0;0;3;3], [::2;0;0;2;0;3]);
      ([::3;1;0;1;0;0;0], [::0;1;0;1;0;0;3]);
      ([::3;0;2;0;0;3;0;2;0], [::2;0;0;2;0;0;2;0]);
      ([::3;0;2;0;0;3;0;2;2], [::2;0;0;2;0;0;2;2]);
      ([::3;0;2;0;0;3;0;2;3], [::2;0;0;2;0;0;2;3])].

Definition cert : pres_cert := [:: add_gen 2 [::0;1;0;1;0;0;0;0;1];
     add_gen 3 [::0;1;0;1;0;0;0];
     add_rel [::1;0;2] [::3;2]
     [:: RTriple 1 2 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;3] [::3;3]
     [:: RTriple 2 2 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 2 1 true];
     add_rel [::3;0;1] [::2]
     [:: RTriple 2 0 false;
         RTriple 1 0 true];
     add_rel [::3;0;3;2] [::2;0;2]
     [:: RTriple 2 0 false;
         RTriple 2 8 false;
         RTriple 1 15 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 2 true];
     add_rel [::3;0;3;3] [::2;0;3]
     [:: RTriple 2 0 false;
         RTriple 2 8 false;
         RTriple 2 15 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 2 true];
     add_rel [::1;0;0;1;0] [::2;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;0;0;1;2] [::2;2]
     [:: RTriple 1 4 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;3] [::2;3]
     [:: RTriple 2 4 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 2 1 true];
     add_rel [::1;0;0;2;0] [::3;0;2;0]
     [:: RTriple 1 3 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 0 2 true;
         RTriple 1 2 true];
     add_rel [::1;0;0;2;2] [::3;0;2;2]
     [:: RTriple 1 3 false;
         RTriple 1 12 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 0 2 true;
         RTriple 1 2 true;
         RTriple 1 3 true];
     add_rel [::1;0;0;2;3] [::3;0;2;3]
     [:: RTriple 1 3 false;
         RTriple 2 12 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 2 0 true;
         RTriple 0 2 true;
         RTriple 1 2 true;
         RTriple 2 3 true];
     add_rel [::1;0;0;3;2] [::2;0;2]
     [:: RTriple 2 3 false;
         RTriple 1 10 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 2 true];
     add_rel [::1;0;0;3;3] [::2;0;3]
     [:: RTriple 2 3 false;
         RTriple 2 10 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 2 2 true];
     add_rel [::2;0;0;1;0] [::1;0;0;2;0]
     [:: RTriple 1 0 false;
         RTriple 0 0 false;
         RTriple 0 3 true;
         RTriple 1 3 true];
     add_rel [::2;0;0;1;2] [::3;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 2 0 true;
         RTriple 1 6 false;
         RTriple 0 2 true;
         RTriple 1 2 true;
         RTriple 1 3 true];
     add_rel [::2;0;0;1;3] [::3;0;2;3]
     [:: RTriple 1 0 false;
         RTriple 2 0 true;
         RTriple 2 6 false;
         RTriple 0 2 true;
         RTriple 1 2 true;
         RTriple 2 3 true];
     add_rel [::3;0;2;0;2] [::2;0;0;3;2]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 5 false;
         RTriple 0 3 true;
         RTriple 2 3 true;
         RTriple 1 4 true];
     add_rel [::3;0;2;0;3] [::2;0;0;3;3]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 5 false;
         RTriple 0 3 true;
         RTriple 2 3 true;
         RTriple 2 4 true];
     add_rel [::2;0;1;0;0;0] [::3;3]
     [:: RTriple 1 0 false;
         RTriple 2 0 true;
         RTriple 2 1 true];
     add_rel [::3;0;3;0;2;0] [::2;0;0;2;0]
     [:: RTriple 2 0 false;
         RTriple 2 8 false;
         RTriple 1 16 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true];
     add_rel [::3;0;3;0;2;2] [::2;0;0;2;2]
     [:: RTriple 2 0 false;
         RTriple 2 8 false;
         RTriple 1 16 false;
         RTriple 1 25 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 1 4 true];
     add_rel [::3;0;3;0;2;3] [::2;0;0;2;3]
     [:: RTriple 2 0 false;
         RTriple 2 8 false;
         RTriple 1 16 false;
         RTriple 2 25 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 2 4 true];
     add_rel [::1;0;0;3;0;2;0] [::2;0;0;2;0]
     [:: RTriple 2 3 false;
         RTriple 1 11 false;
         RTriple 0 11 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true];
     add_rel [::1;0;0;3;0;2;2] [::2;0;0;2;2]
     [:: RTriple 2 3 false;
         RTriple 1 11 false;
         RTriple 1 20 false;
         RTriple 0 11 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 1 4 true];
     add_rel [::1;0;0;3;0;2;3] [::2;0;0;2;3]
     [:: RTriple 2 3 false;
         RTriple 1 11 false;
         RTriple 2 20 false;
         RTriple 0 11 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 2 4 true];
     add_rel [::3;0;2;0;0;2;0] [::2;0;0;3;0;2;0]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 6 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 2 3 true;
         RTriple 0 5 true;
         RTriple 1 5 true];
     add_rel [::3;0;2;0;0;2;2] [::2;0;0;3;0;2;2]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 6 false;
         RTriple 1 15 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 2 3 true;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     add_rel [::3;0;2;0;0;2;3] [::2;0;0;3;0;2;3]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 6 false;
         RTriple 2 15 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 2 3 true;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 2 6 true];
     add_rel [::3;0;2;0;0;3;2] [::2;0;0;2;0;2]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 6 false;
         RTriple 1 13 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 1 5 true];
     add_rel [::3;0;2;0;0;3;3] [::2;0;0;2;0;3]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 6 false;
         RTriple 2 13 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 2 5 true];
     add_rel [::3;1;0;1;0;0;0] [::0;1;0;1;0;0;3]
     [:: RTriple 2 0 false;
         RTriple 2 6 true];
     add_rel [::3;0;2;0;0;3;0;2;0] [::2;0;0;2;0;0;2;0]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 6 false;
         RTriple 1 14 false;
         RTriple 0 14 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 0 6 true;
         RTriple 1 6 true];
     add_rel [::3;0;2;0;0;3;0;2;2] [::2;0;0;2;0;0;2;2]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 6 false;
         RTriple 1 14 false;
         RTriple 1 23 false;
         RTriple 0 14 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 1 7 true];
     add_rel [::3;0;2;0;0;3;0;2;3] [::2;0;0;2;0;0;2;3]
     [:: RTriple 2 0 false;
         RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 2 6 false;
         RTriple 1 14 false;
         RTriple 2 23 false;
         RTriple 0 14 false;
         RTriple 0 6 false;
         RTriple 0 3 true;
         RTriple 1 3 true;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 2 7 true];
     rm_rel 0
     [:: RTriple 7 0 true;
         RTriple 4 0 false;
         RTriple 1 0 false];
     rm_rel 0
     [:: RTriple 0 0 true;
         RTriple 3 0 true]].

Definition final_order := [::0;1;2;3].

Load "theories/certs/footer.v".
