(* Autogenerated cert for < ba | baabaabba = aaaabbaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;0;0;1;0;0;1;1;0], [::0;0;0;0;1;1;0;0])].

Definition present_final := make_pres [::1;0;2]
  [:: ([::0;0;1;1], [::2]);
      ([::1;0;0;1;2;0], [::0;0;2;0;0]);
      ([::1;0;0;1;2;2], [::0;0;2;0;2]);
      ([::0;0;1;0;0;2;0;0], [::2;0;0;1;2;0]);
      ([::0;0;1;0;0;2;0;2], [::2;0;0;1;2;2]);
      ([::2;0;0;1;2;0;1;1], [::0;0;1;0;0;2;2]);
      ([::0;0;2;0;0;0;1;2;0;1;1], [::1;0;0;1;0;0;1;0;0;2;2]);
      ([::0;0;1;0;0;0;0;1;0;0;2;2], [::2;0;0;1;2;0;1;2;0;1;1]);
      ([::0;0;1;0;0;2;2;0;0;1;2;0], [::2;0;0;1;2;0;1;0;0;2;0;0]);
      ([::0;0;1;0;0;2;2;0;0;1;2;2], [::2;0;0;1;2;0;1;0;0;2;0;2]);
      ([::1;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2], [::0;0;2;0;1;0;0;1;0;0;1;0;0;2;2]);
      ([::0;0;1;0;0;2;1;0;0;1;0;0;1;0;0;2;2], [::2;0;0;1;2;0;2;0;0;0;1;2;0;1;1]);
      ([::0;0;1;0;0;2;0;1;0;0;1;0;0;1;0;0;2;2], [::2;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2]);
      ([::0;0;1;0;0;2;2;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2], [::2;0;0;1;2;0;1;0;0;2;0;1;0;0;1;0;0;1;0;0;2;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;1;1];
     add_rel [::1;0;0;1;2;0] [::0;0;2;0;0]
     [:: RTriple 1 4 false;
         RTriple 0 0 true;
         RTriple 1 2 true];
     add_rel [::1;0;0;1;2;2] [::0;0;2;0;2]
     [:: RTriple 1 4 false;
         RTriple 1 8 false;
         RTriple 0 0 true;
         RTriple 1 2 true;
         RTriple 1 4 true];
     add_rel [::0;0;1;0;0;2;0;0] [::2;0;0;1;2;0]
     [:: RTriple 1 5 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true];
     add_rel [::0;0;1;0;0;2;0;2] [::2;0;0;1;2;2]
     [:: RTriple 1 5 false;
         RTriple 1 10 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::2;0;0;1;2;0;1;1] [::0;0;1;0;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 7 false;
         RTriple 0 3 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     add_rel [::0;0;2;0;0;0;1;2;0;1;1] [::1;0;0;1;0;0;1;0;0;2;2]
     [:: RTriple 1 2 false;
         RTriple 0 0 false;
         RTriple 1 11 false;
         RTriple 0 7 true;
         RTriple 1 9 true;
         RTriple 1 10 true];
     add_rel [::0;0;1;0;0;0;0;1;0;0;2;2] [::2;0;0;1;2;0;1;2;0;1;1]
     [:: RTriple 1 10 false;
         RTriple 1 14 false;
         RTriple 0 8 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 7 true];
     add_rel [::0;0;1;0;0;2;2;0;0;1;2;0] [::2;0;0;1;2;0;1;0;0;2;0;0]
     [:: RTriple 1 5 false;
         RTriple 1 9 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 11 false;
         RTriple 0 7 true;
         RTriple 1 9 true];
     add_rel [::0;0;1;0;0;2;2;0;0;1;2;2] [::2;0;0;1;2;0;1;0;0;2;0;2]
     [:: RTriple 1 5 false;
         RTriple 1 9 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 11 false;
         RTriple 1 15 false;
         RTriple 0 7 true;
         RTriple 1 9 true;
         RTriple 1 11 true];
     add_rel [::1;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2] [::0;0;2;0;1;0;0;1;0;0;1;0;0;2;2]
     [:: RTriple 1 4 false;
         RTriple 1 17 false;
         RTriple 1 21 false;
         RTriple 0 15 false;
         RTriple 0 8 true;
         RTriple 0 0 true;
         RTriple 1 2 true;
         RTriple 0 4 false;
         RTriple 0 11 true;
         RTriple 1 13 true;
         RTriple 1 14 true];
     add_rel [::0;0;1;0;0;2;1;0;0;1;0;0;1;0;0;2;2] [::2;0;0;1;2;0;2;0;0;0;1;2;0;1;1]
     [:: RTriple 1 5 false;
         RTriple 1 18 false;
         RTriple 1 22 false;
         RTriple 0 16 false;
         RTriple 0 9 true;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 6 true;
         RTriple 1 11 true];
     add_rel [::0;0;1;0;0;2;0;1;0;0;1;0;0;1;0;0;2;2] [::2;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2]
     [:: RTriple 1 5 false;
         RTriple 1 19 false;
         RTriple 1 23 false;
         RTriple 0 17 false;
         RTriple 0 10 true;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 0 5 false;
         RTriple 0 12 true;
         RTriple 1 14 true;
         RTriple 1 15 true];
     add_rel [::0;0;1;0;0;2;2;0;0;1;2;1;0;0;1;0;0;1;0;0;2;2] [::2;0;0;1;2;0;1;0;0;2;0;1;0;0;1;0;0;1;0;0;2;2]
     [:: RTriple 1 5 false;
         RTriple 1 9 false;
         RTriple 0 3 false;
         RTriple 1 0 true;
         RTriple 1 4 true;
         RTriple 1 11 false;
         RTriple 1 24 false;
         RTriple 1 28 false;
         RTriple 0 22 false;
         RTriple 0 15 true;
         RTriple 0 7 true;
         RTriple 1 9 true;
         RTriple 0 11 false;
         RTriple 0 18 true;
         RTriple 1 20 true;
         RTriple 1 21 true];
     rm_rel 0
     [:: RTriple 0 4 true;
         RTriple 1 0 true;
         RTriple 0 2 false]].

Definition final_order := [::1;2;0].

Load "theories/certs/footer.v".
