(* Autogenerated cert for < ab | baabbaabaa = aaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::1;0;0;1;1;0;0;1;0;0], [::0;0;0])].

Definition present_final := make_pres [::0;1]
  [:: ([::1;0;0;1;1;0;0;1;0;0], [::0;0;0]);
      ([::1;0;0;1;1;0;0;0;0;0], [::0;0;0;1;1;0;0;1;0;0])].

Definition cert : pres_cert := [:: add_rel [::1;0;0;1;1;0;0;0;0;0] [::0;0;0;1;1;0;0;1;0;0]
     [:: RTriple 0 7 false;
         RTriple 0 0 true]].

Definition final_order := [::0;1].

Load "theories/certs/footer.v".
