(* Autogenerated cert for < ab | baababba = aabaababaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::1;0;0;1;0;1;1;0], [::0;0;1;0;0;1;0;1;0;0])].

Definition present_final := make_pres [::0;1;2]
  [:: ([::0;1;0;0;1;0;1;0], [::2]);
      ([::0;1;0;0;1;2], [::2;0;1;0;1;0]);
      ([::0;1;0;0;1;0;1;2], [::2;1;0;0;1;0;1;0]);
      ([::1;0;0;1;0;1;1;0], [::0;2;0]);
      ([::1;0;0;1;0;1;1;2], [::0;2;2]);
      ([::0;1;0;0;1;0;0;2;0], [::2;0;1;0;1;1;0]);
      ([::0;1;0;0;1;0;0;2;2], [::2;0;1;0;1;1;2]);
      ([::1;0;0;1;0;1;0;2;0], [::0;2;0;0;1;0;1;1;0]);
      ([::1;0;0;1;0;1;0;2;2], [::0;2;0;0;1;0;1;1;2]);
      ([::0;0;2;0;0;1;0;1;1;0], [::2;2;0]);
      ([::0;0;2;0;0;1;0;1;1;2], [::2;2;2]);
      ([::0;0;2;0;0;1;0;1;0;2;0], [::2;2;0;0;1;0;1;1;0]);
      ([::0;0;2;0;0;1;0;1;0;2;2], [::2;2;0;0;1;0;1;1;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;1;0;0;1;0;1;0];
     add_rel [::0;1;0;0;1;2] [::2;0;1;0;1;0]
     [:: RTriple 1 5 false;
         RTriple 1 0 true];
     add_rel [::0;1;0;0;1;0;1;2] [::2;1;0;0;1;0;1;0]
     [:: RTriple 1 7 false;
         RTriple 1 0 true];
     add_rel [::1;0;0;1;0;1;1;0] [::0;2;0]
     [:: RTriple 0 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;0;1;1;2] [::0;2;2]
     [:: RTriple 1 7 false;
         RTriple 0 0 true;
         RTriple 1 1 true;
         RTriple 1 2 true];
     add_rel [::0;1;0;0;1;0;0;2;0] [::2;0;1;0;1;1;0]
     [:: RTriple 1 7 false;
         RTriple 0 6 false;
         RTriple 1 0 true];
     add_rel [::0;1;0;0;1;0;0;2;2] [::2;0;1;0;1;1;2]
     [:: RTriple 1 7 false;
         RTriple 1 15 false;
         RTriple 0 6 false;
         RTriple 1 0 true;
         RTriple 1 6 true];
     add_rel [::1;0;0;1;0;1;0;2;0] [::0;2;0;0;1;0;1;1;0]
     [:: RTriple 1 7 false;
         RTriple 0 6 false;
         RTriple 0 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;0;1;0;2;2] [::0;2;0;0;1;0;1;1;2]
     [:: RTriple 1 7 false;
         RTriple 1 15 false;
         RTriple 0 6 false;
         RTriple 0 0 true;
         RTriple 1 1 true;
         RTriple 1 8 true];
     add_rel [::0;0;2;0;0;1;0;1;1;0] [::2;2;0]
     [:: RTriple 1 2 false;
         RTriple 0 1 false;
         RTriple 0 7 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::0;0;2;0;0;1;0;1;1;2] [::2;2;2]
     [:: RTriple 1 2 false;
         RTriple 0 1 false;
         RTriple 1 14 false;
         RTriple 0 7 true;
         RTriple 1 0 true;
         RTriple 1 1 true;
         RTriple 1 2 true];
     add_rel [::0;0;2;0;0;1;0;1;0;2;0] [::2;2;0;0;1;0;1;1;0]
     [:: RTriple 1 2 false;
         RTriple 0 1 false;
         RTriple 1 14 false;
         RTriple 0 13 false;
         RTriple 0 7 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::0;0;2;0;0;1;0;1;0;2;2] [::2;2;0;0;1;0;1;1;2]
     [:: RTriple 1 2 false;
         RTriple 0 1 false;
         RTriple 1 14 false;
         RTriple 1 22 false;
         RTriple 0 13 false;
         RTriple 0 7 true;
         RTriple 1 0 true;
         RTriple 1 1 true;
         RTriple 1 8 true];
     rm_rel 0
     [:: RTriple 3 0 true;
         RTriple 0 1 false]].

Definition final_order := [::2;0;1].

Load "theories/certs/footer.v".
