(* Autogenerated cert for < ab | baabaaaa = aaaaaaaaaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::1;0;0;1;0;0;0;0], [::0;0;0;0;0;0;0;0;0;0])].

Definition present_final := make_pres [::0;1;2]
  [:: ([::0;0;0;0;0;0;0;0;0], [::2]);
      ([::2;0], [::0;2]);
      ([::1;0;0;1;0;2], [::0;1;0;0;1;2]);
      ([::2;1;0;0;1;2], [::1;0;0;1;2;2]);
      ([::0;0;0;0;0;0;2], [::1;0;0;1;2]);
      ([::1;0;0;1;0;0;2], [::0;1;0;0;1;0;2]);
      ([::0;0;0;1;0;0;1;2], [::2;2]);
      ([::1;0;0;1;0;0;0;0], [::2;0]);
      ([::1;0;0;1;0;0;0;2], [::2;2]);
      ([::1;0;0;1;1;0;0;1;2], [::0;0;0;2;2]);
      ([::1;0;0;1;0;1;0;0;1;2], [::0;0;0;0;2;2]);
      ([::1;0;0;1;0;0;1;0;0;1;2], [::0;0;0;0;0;2;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;0;0;0;0;0;0;0];
     add_rel [::2;0] [::0;2]
     [:: RTriple 1 0 false;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;0;2] [::0;1;0;0;1;2]
     [:: RTriple 1 5 false;
         RTriple 0 0 true;
         RTriple 0 1 false;
         RTriple 1 5 true];
     add_rel [::2;1;0;0;1;2] [::1;0;0;1;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 13 false;
         RTriple 0 9 true;
         RTriple 0 0 false;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::0;0;0;0;0;0;2] [::1;0;0;1;2]
     [:: RTriple 1 6 false;
         RTriple 0 0 false;
         RTriple 1 4 true];
     add_rel [::1;0;0;1;0;0;2] [::0;1;0;0;1;0;2]
     [:: RTriple 1 6 false;
         RTriple 0 0 true;
         RTriple 0 1 false;
         RTriple 1 6 true];
     add_rel [::0;0;0;1;0;0;1;2] [::2;2]
     [:: RTriple 1 7 false;
         RTriple 0 3 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;0;0;0;0] [::2;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;0;0;1;0;0;0;2] [::2;2]
     [:: RTriple 1 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;0;1;1;0;0;1;2] [::0;0;0;2;2]
     [:: RTriple 1 8 false;
         RTriple 0 4 true;
         RTriple 0 0 true;
         RTriple 1 3 true;
         RTriple 1 4 true];
     add_rel [::1;0;0;1;0;1;0;0;1;2] [::0;0;0;0;2;2]
     [:: RTriple 1 9 false;
         RTriple 0 5 true;
         RTriple 0 0 true;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::1;0;0;1;0;0;1;0;0;1;2] [::0;0;0;0;0;2;2]
     [:: RTriple 1 10 false;
         RTriple 0 6 true;
         RTriple 0 0 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     rm_rel 0
     [:: RTriple 7 0 true;
         RTriple 0 0 false]].

Definition final_order := [::0;1;2].

Load "theories/certs/footer.v".
