(* Autogenerated cert for < ba | babbbbbaba = aaaaaba > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;0;1;1;1;1;1;0;1;0], [::0;0;0;0;0;1;0])].

Definition present_final := make_pres [::1;0;2]
  [:: ([::0;0;0;0;0;1], [::2]);
      ([::1;0;1;1;1;1;1;0;1;0], [::2;0]);
      ([::1;0;1;1;1;1;1;0;1;2], [::2;2]);
      ([::1;0;1;1;1;1;1;0;2;0], [::0;0;0;0;0;2;0]);
      ([::1;0;1;1;1;1;1;0;2;2], [::0;0;0;0;0;2;2]);
      ([::2;0;1;1;1;1;1;0;1;0], [::1;0;1;1;1;1;1;0;2;0]);
      ([::2;0;1;1;1;1;1;0;1;2], [::0;0;0;0;0;2;2]);
      ([::0;0;0;0;0;0;0;0;0;0;2;0], [::2;0;1;1;1;1;1;0;2;0]);
      ([::0;0;0;0;0;0;0;0;0;0;2;2], [::2;0;1;1;1;1;1;0;2;2]);
      ([::1;0;1;1;1;1;1;0;0;0;0;0;0;2;0], [::2;0;1;1;1;1;1;0;2;0]);
      ([::1;0;1;1;1;1;1;0;0;0;0;0;0;2;2], [::2;0;1;1;1;1;1;0;2;2]);
      ([::2;0;1;1;1;1;1;0;0;0;0;0;0;2;0], [::0;0;0;0;0;2;0;1;1;1;1;1;0;2;0]);
      ([::2;0;1;1;1;1;1;0;0;0;0;0;0;2;2], [::0;0;0;0;0;2;0;1;1;1;1;1;0;2;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;0;0;0;1];
     add_rel [::1;0;1;1;1;1;1;0;1;0] [::2;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;0;1;1;1;1;1;0;1;2] [::2;2]
     [:: RTriple 1 9 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;1;1;1;1;1;0;2;0] [::0;0;0;0;0;2;0]
     [:: RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 0 0 true;
         RTriple 0 5 true;
         RTriple 1 5 true];
     add_rel [::1;0;1;1;1;1;1;0;2;2] [::0;0;0;0;0;2;2]
     [:: RTriple 1 8 false;
         RTriple 1 14 false;
         RTriple 0 8 false;
         RTriple 0 0 true;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     add_rel [::2;0;1;1;1;1;1;0;1;0] [::1;0;1;1;1;1;1;0;2;0]
     [:: RTriple 1 0 false;
         RTriple 0 0 false;
         RTriple 0 8 true;
         RTriple 1 8 true];
     add_rel [::2;0;1;1;1;1;1;0;1;2] [::0;0;0;0;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 14 false;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 1 6 true];
     add_rel [::0;0;0;0;0;0;0;0;0;0;2;0] [::2;0;1;1;1;1;1;0;2;0]
     [:: RTriple 1 10 false;
         RTriple 0 10 false;
         RTriple 0 5 false;
         RTriple 1 0 true;
         RTriple 0 8 true;
         RTriple 1 8 true];
     add_rel [::0;0;0;0;0;0;0;0;0;0;2;2] [::2;0;1;1;1;1;1;0;2;2]
     [:: RTriple 1 10 false;
         RTriple 1 16 false;
         RTriple 0 10 false;
         RTriple 0 5 false;
         RTriple 1 0 true;
         RTriple 0 8 true;
         RTriple 1 8 true;
         RTriple 1 9 true];
     add_rel [::1;0;1;1;1;1;1;0;0;0;0;0;0;2;0] [::2;0;1;1;1;1;1;0;2;0]
     [:: RTriple 1 13 false;
         RTriple 0 13 false;
         RTriple 0 8 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 8 true;
         RTriple 1 8 true];
     add_rel [::1;0;1;1;1;1;1;0;0;0;0;0;0;2;2] [::2;0;1;1;1;1;1;0;2;2]
     [:: RTriple 1 13 false;
         RTriple 1 19 false;
         RTriple 0 13 false;
         RTriple 0 8 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 8 true;
         RTriple 1 8 true;
         RTriple 1 9 true];
     add_rel [::2;0;1;1;1;1;1;0;0;0;0;0;0;2;0] [::0;0;0;0;0;2;0;1;1;1;1;1;0;2;0]
     [:: RTriple 1 0 false;
         RTriple 1 18 false;
         RTriple 0 18 false;
         RTriple 0 13 false;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 0 13 true;
         RTriple 1 13 true];
     add_rel [::2;0;1;1;1;1;1;0;0;0;0;0;0;2;2] [::0;0;0;0;0;2;0;1;1;1;1;1;0;2;2]
     [:: RTriple 1 0 false;
         RTriple 1 18 false;
         RTriple 1 24 false;
         RTriple 0 18 false;
         RTriple 0 13 false;
         RTriple 0 5 true;
         RTriple 1 5 true;
         RTriple 0 13 true;
         RTriple 1 13 true;
         RTriple 1 14 true];
     rm_rel 0
     [:: RTriple 1 0 true;
         RTriple 0 0 false]].

Definition final_order := [::1;0;2].

Load "theories/certs/footer.v".
