(* Autogenerated cert for < ab | babbaabba = abbaabaaba > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::0;1]
  [:: ([::1;0;1;1;0;0;1;1;0], [::0;1;1;0;0;1;0;0;1;0])].

Definition present_final := make_pres [::0;1;2;3]
  [:: ([::0;0;1;0;0], [::3]);
      ([::0;0;1;3], [::3;1;0;0]);
      ([::0;0;1;0;2], [::3;1;1;3;1]);
      ([::0;0;1;0;3], [::3;0;1;0;0]);
      ([::0;1;1;3;1], [::2]);
      ([::1;0;1;1;0;2], [::2;3;1]);
      ([::0;1;1;3;2;3;1], [::2;0;1;1;0;2]);
      ([::1;0;1;1;0;0;1;1;0], [::2;0]);
      ([::1;0;1;1;0;0;1;1;2], [::2;2]);
      ([::1;0;1;1;0;0;1;1;3], [::2;3]);
      ([::1;0;1;1;0;0;1;2;0], [::0;1;1;3;2;0]);
      ([::1;0;1;1;0;0;1;2;2], [::0;1;1;3;2;2]);
      ([::1;0;1;1;0;0;1;2;3], [::0;1;1;3;2;3]);
      ([::2;0;1;1;0;0;1;1;0], [::1;0;1;1;0;0;1;2;0]);
      ([::2;0;1;1;0;0;1;1;2], [::0;1;1;3;2;2]);
      ([::2;0;1;1;0;0;1;1;3], [::0;1;1;3;2;3]);
      ([::0;1;1;3;0;1;1;3;2;0], [::2;0;1;1;0;0;1;2;0]);
      ([::0;1;1;3;0;1;1;3;2;2], [::2;0;1;1;0;0;1;2;2]);
      ([::0;1;1;3;0;1;1;3;2;3], [::2;0;1;1;0;0;1;2;3]);
      ([::2;0;1;1;0;0;1;2;3;1], [::0;1;1;3;2;0;1;1;0;2]);
      ([::2;0;1;1;0;2;0;1;1;0;2], [::0;1;1;3;2;3;2;3;1]);
      ([::1;0;1;1;0;0;1;0;1;1;3;2;0], [::2;0;1;1;0;0;1;2;0]);
      ([::1;0;1;1;0;0;1;0;1;1;3;2;2], [::2;0;1;1;0;0;1;2;2]);
      ([::1;0;1;1;0;0;1;0;1;1;3;2;3], [::2;0;1;1;0;0;1;2;3]);
      ([::2;0;1;1;0;0;1;0;1;1;3;2;0], [::0;1;1;3;2;0;1;1;0;0;1;2;0]);
      ([::2;0;1;1;0;0;1;0;1;1;3;2;2], [::0;1;1;3;2;0;1;1;0;0;1;2;2]);
      ([::2;0;1;1;0;0;1;0;1;1;3;2;3], [::0;1;1;3;2;0;1;1;0;0;1;2;3]);
      ([::2;0;1;1;0;2;0;1;1;0;0;1;2;0], [::0;1;1;3;2;3;0;1;1;3;2;0]);
      ([::2;0;1;1;0;2;0;1;1;0;0;1;2;2], [::0;1;1;3;2;3;0;1;1;3;2;2]);
      ([::2;0;1;1;0;2;0;1;1;0;0;1;2;3], [::0;1;1;3;2;3;0;1;1;3;2;3])].

Definition cert : pres_cert := [:: add_gen 2 [::0;1;1;0;0;1;0;0;1];
     add_gen 3 [::0;0;1;0;0];
     add_rel [::0;0;1;3] [::3;1;0;0]
     [:: RTriple 2 3 false;
         RTriple 2 0 true];
     add_rel [::0;0;1;0;2] [::3;1;1;3;1]
     [:: RTriple 1 4 false;
         RTriple 2 0 true;
         RTriple 2 3 true];
     add_rel [::0;0;1;0;3] [::3;0;1;0;0]
     [:: RTriple 2 4 false;
         RTriple 2 0 true];
     add_rel [::0;1;1;3;1] [::2]
     [:: RTriple 2 3 false;
         RTriple 1 0 true];
     add_rel [::1;0;1;1;0;2] [::2;3;1]
     [:: RTriple 1 5 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 2 1 true];
     add_rel [::0;1;1;3;2;3;1] [::2;0;1;1;0;2]
     [:: RTriple 2 3 false;
         RTriple 1 8 false;
         RTriple 2 17 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 5 true];
     add_rel [::1;0;1;1;0;0;1;1;0] [::2;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;0;1;1;0;0;1;1;2] [::2;2]
     [:: RTriple 1 8 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::1;0;1;1;0;0;1;1;3] [::2;3]
     [:: RTriple 2 8 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 2 1 true];
     add_rel [::1;0;1;1;0;0;1;2;0] [::0;1;1;3;2;0]
     [:: RTriple 1 7 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 2 3 true;
         RTriple 0 4 true;
         RTriple 1 4 true];
     add_rel [::1;0;1;1;0;0;1;2;2] [::0;1;1;3;2;2]
     [:: RTriple 1 7 false;
         RTriple 1 16 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 2 3 true;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::1;0;1;1;0;0;1;2;3] [::0;1;1;3;2;3]
     [:: RTriple 1 7 false;
         RTriple 2 16 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 2 3 true;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true];
     add_rel [::2;0;1;1;0;0;1;1;0] [::1;0;1;1;0;0;1;2;0]
     [:: RTriple 1 0 false;
         RTriple 0 0 false;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::2;0;1;1;0;0;1;1;2] [::0;1;1;3;2;2]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 12 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 1 5 true];
     add_rel [::2;0;1;1;0;0;1;1;3] [::0;1;1;3;2;3]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 2 12 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true];
     add_rel [::0;1;1;3;0;1;1;3;2;0] [::2;0;1;1;0;0;1;2;0]
     [:: RTriple 2 3 false;
         RTriple 2 11 false;
         RTriple 1 16 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::0;1;1;3;0;1;1;3;2;2] [::2;0;1;1;0;0;1;2;2]
     [:: RTriple 2 3 false;
         RTriple 2 11 false;
         RTriple 1 16 false;
         RTriple 1 25 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 8 true];
     add_rel [::0;1;1;3;0;1;1;3;2;3] [::2;0;1;1;0;0;1;2;3]
     [:: RTriple 2 3 false;
         RTriple 2 11 false;
         RTriple 1 16 false;
         RTriple 2 25 false;
         RTriple 0 16 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 2 8 true];
     add_rel [::2;0;1;1;0;0;1;2;3;1] [::0;1;1;3;2;0;1;1;0;2]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 11 false;
         RTriple 2 20 false;
         RTriple 0 11 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 1 9 true];
     add_rel [::2;0;1;1;0;2;0;1;1;0;2] [::0;1;1;3;2;3;2;3;1]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 9 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true;
         RTriple 1 11 false;
         RTriple 0 6 true;
         RTriple 1 6 true;
         RTriple 2 7 true];
     add_rel [::1;0;1;1;0;0;1;0;1;1;3;2;0] [::2;0;1;1;0;0;1;2;0]
     [:: RTriple 2 10 false;
         RTriple 1 15 false;
         RTriple 0 15 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true];
     add_rel [::1;0;1;1;0;0;1;0;1;1;3;2;2] [::2;0;1;1;0;0;1;2;2]
     [:: RTriple 2 10 false;
         RTriple 1 15 false;
         RTriple 1 24 false;
         RTriple 0 15 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 1 8 true];
     add_rel [::1;0;1;1;0;0;1;0;1;1;3;2;3] [::2;0;1;1;0;0;1;2;3]
     [:: RTriple 2 10 false;
         RTriple 1 15 false;
         RTriple 2 24 false;
         RTriple 0 15 false;
         RTriple 0 7 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 0 7 true;
         RTriple 1 7 true;
         RTriple 2 8 true];
     add_rel [::2;0;1;1;0;0;1;0;1;1;3;2;0] [::0;1;1;3;2;0;1;1;0;0;1;2;0]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 2 14 false;
         RTriple 1 19 false;
         RTriple 0 19 false;
         RTriple 0 11 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 0 11 true;
         RTriple 1 11 true];
     add_rel [::2;0;1;1;0;0;1;0;1;1;3;2;2] [::0;1;1;3;2;0;1;1;0;0;1;2;2]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 2 14 false;
         RTriple 1 19 false;
         RTriple 1 28 false;
         RTriple 0 19 false;
         RTriple 0 11 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 0 11 true;
         RTriple 1 11 true;
         RTriple 1 12 true];
     add_rel [::2;0;1;1;0;0;1;0;1;1;3;2;3] [::0;1;1;3;2;0;1;1;0;0;1;2;3]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 2 14 false;
         RTriple 1 19 false;
         RTriple 2 28 false;
         RTriple 0 19 false;
         RTriple 0 11 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 0 11 true;
         RTriple 1 11 true;
         RTriple 2 12 true];
     add_rel [::2;0;1;1;0;2;0;1;1;0;0;1;2;0] [::0;1;1;3;2;3;0;1;1;3;2;0]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 9 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true;
         RTriple 1 13 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 2 9 true;
         RTriple 0 10 true;
         RTriple 1 10 true];
     add_rel [::2;0;1;1;0;2;0;1;1;0;0;1;2;2] [::0;1;1;3;2;3;0;1;1;3;2;2]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 9 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true;
         RTriple 1 13 false;
         RTriple 1 22 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 2 9 true;
         RTriple 0 10 true;
         RTriple 1 10 true;
         RTriple 1 11 true];
     add_rel [::2;0;1;1;0;2;0;1;1;0;0;1;2;3] [::0;1;1;3;2;3;0;1;1;3;2;3]
     [:: RTriple 1 0 false;
         RTriple 2 3 true;
         RTriple 1 9 false;
         RTriple 0 4 true;
         RTriple 1 4 true;
         RTriple 2 5 true;
         RTriple 1 13 false;
         RTriple 2 22 false;
         RTriple 0 13 false;
         RTriple 0 6 true;
         RTriple 2 9 true;
         RTriple 0 10 true;
         RTriple 1 10 true;
         RTriple 2 11 true];
     rm_rel 0
     [:: RTriple 8 0 true;
         RTriple 5 0 false;
         RTriple 1 3 false];
     rm_rel 0
     [:: RTriple 0 3 true;
         RTriple 4 0 true]].

Definition final_order := [::1;3;0;2].

Load "theories/certs/footer.v".
