(* Autogenerated cert for < ba | bbaaabbbba = aaabbbbaa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;1;0;0;0;1;1;1;1;0], [::0;0;0;1;1;1;1;0;0])].

Definition present_final := make_pres [::1;0;2]
  [:: ([::1;1;1;1;0], [::2]);
      ([::0;0;0;2;0;0], [::2;0;0;2]);
      ([::1;1;0;0;0;2], [::0;0;0;2;0]);
      ([::1;1;2;0;0;2], [::2;0;0;2;0]);
      ([::0;0;0;2;2;0;0;2], [::2;0;0;2;0;2;0;0]);
      ([::0;0;0;2;0;2;0;0;2], [::2;0;0;2;0;0;2;0;0])].

Definition cert : pres_cert := [:: add_gen 2 [::1;1;1;1;0];
     add_rel [::0;0;0;2;0;0] [::2;0;0;2]
     [:: RTriple 1 3 false;
         RTriple 0 0 false;
         RTriple 0 2 false;
         RTriple 1 0 true;
         RTriple 1 3 true];
     add_rel [::1;1;0;0;0;2] [::0;0;0;2;0]
     [:: RTriple 1 5 false;
         RTriple 0 0 true;
         RTriple 1 3 true];
     add_rel [::1;1;2;0;0;2] [::2;0;0;2;0]
     [:: RTriple 1 2 false;
         RTriple 1 9 false;
         RTriple 0 4 true;
         RTriple 1 0 true;
         RTriple 1 3 true];
     add_rel [::0;0;0;2;2;0;0;2] [::2;0;0;2;0;2;0;0]
     [:: RTriple 1 3 false;
         RTriple 1 8 false;
         RTriple 1 15 false;
         RTriple 0 10 true;
         RTriple 0 8 true;
         RTriple 0 0 false;
         RTriple 0 2 false;
         RTriple 1 0 true;
         RTriple 1 3 true;
         RTriple 1 5 true];
     add_rel [::0;0;0;2;0;2;0;0;2] [::2;0;0;2;0;0;2;0;0]
     [:: RTriple 1 3 false;
         RTriple 0 0 false;
         RTriple 1 10 false;
         RTriple 1 17 false;
         RTriple 0 12 true;
         RTriple 0 10 true;
         RTriple 0 2 false;
         RTriple 1 0 true;
         RTriple 1 3 true;
         RTriple 1 6 true];
     rm_rel 0
     [:: RTriple 0 5 true;
         RTriple 2 0 true;
         RTriple 0 3 false]].

Definition final_order := [::1;2;0].

Load "theories/certs/footer.v".
