(* Autogenerated cert for < ba | bbabba = aaaabababa > *)

Load "theories/certs/header.v".

Definition present_entry := make_pres [::1;0]
  [:: ([::1;1;0;1;1;0], [::0;0;0;0;1;0;1;0;1;0])].

Definition present_final := make_pres [::1;0;2]
  [:: ([::0;0;0;0;1;0;1;0;1], [::2]);
      ([::1;1;0;2;0], [::2;0;1;1;0]);
      ([::1;1;0;2;2], [::2;0;1;1;2]);
      ([::1;1;0;1;1;0], [::2;0]);
      ([::1;1;0;1;1;2], [::2;2]);
      ([::0;0;0;0;1;0;1;0;2;0], [::2;1;0;1;1;0]);
      ([::0;0;0;0;1;0;1;0;2;2], [::2;1;0;1;1;2])].

Definition cert : pres_cert := [:: add_gen 2 [::0;0;0;0;1;0;1;0;1];
     add_rel [::1;1;0;2;0] [::2;0;1;1;0]
     [:: RTriple 1 3 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;1;0;2;2] [::2;0;1;1;2]
     [:: RTriple 1 3 false;
         RTriple 1 12 false;
         RTriple 0 3 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 4 true];
     add_rel [::1;1;0;1;1;0] [::2;0]
     [:: RTriple 0 0 true;
         RTriple 1 0 true];
     add_rel [::1;1;0;1;1;2] [::2;2]
     [:: RTriple 1 5 false;
         RTriple 0 0 true;
         RTriple 1 0 true;
         RTriple 1 1 true];
     add_rel [::0;0;0;0;1;0;1;0;2;0] [::2;1;0;1;1;0]
     [:: RTriple 1 8 false;
         RTriple 0 8 false;
         RTriple 1 0 true];
     add_rel [::0;0;0;0;1;0;1;0;2;2] [::2;1;0;1;1;2]
     [:: RTriple 1 8 false;
         RTriple 1 17 false;
         RTriple 0 8 false;
         RTriple 1 0 true;
         RTriple 1 5 true];
     rm_rel 0
     [:: RTriple 3 0 true;
         RTriple 0 0 false]].

Definition final_order := [::2;1;0].

Load "theories/certs/footer.v".
