(* Autogenerated cert for < abc | aa =  > *)

Load "header.v".

Definition present_entry := make_pres [::0;1;2]
  [:: ([::0;0], [::]);
      ([::1;1], [::]);
      ([::2;2], [::]);
      ([::0;1;0], [::1;0;1]);
      ([::1;2;1], [::2;1;2]);
      ([::0;2], [::2;0])].

Definition present_final := make_pres [::0;1;2]
  [:: ([::0;0], [::]);
      ([::1;1], [::]);
      ([::2;2], [::]);
      ([::1;0;1], [::0;1;0]);
      ([::2;0], [::0;2]);
      ([::2;1;2], [::1;2;1]);
      ([::2;1;0;2], [::1;2;1;0])].

Definition cert : pres_cert := [:: add_rel [::1;0;1] [::0;1;0]
     [:: RTriple 3 0 false];
     add_rel [::2;0] [::0;2]
     [:: RTriple 5 0 false];
     add_rel [::2;1;2] [::1;2;1]
     [:: RTriple 4 0 false];
     add_rel [::2;1;0;2] [::1;2;1;0]
     [:: RTriple 5 2 true;
         RTriple 8 0 true];
     rm_rel 3
     [:: RTriple 5 0 false];
     rm_rel 3
     [:: RTriple 6 0 false];
     rm_rel 3
     [:: RTriple 4 0 false]].

Definition final_order := [::0;1;2].

Load "footer_trie.v".

From mathcomp Require Import ssrnat path.
Require Import enumnf.

Goal foldl (fun acc s => acc + size_int s) 0
  (traject (enum_normal_next_trie present_final) [:: [::]] 10) = 24.
Proof.
by native_cast_no_check (erefl 24).
Time Qed.
